#!/bin/bash
######################################################################
# Avenir Testing Framework installer
#
# Nevin Jojo, 1 March 2018
######################################################################


######################################################################
# main

#There are only three installations that are required by main.rb to execute the tests.
#They are: ruby, yaml, selenium-webdriver
######################################################################

echo "######################################################################"
echo "Welcome to Avenir Testing Framework Installer"
echo "######################################################################"

# make directories

mkdir -p results
mkdir -p screenshots
mkdir -p scripts

# install brew

COUNT=`/usr/local/bin/brew --version | wc -l`
if [ "${COUNT}" == 0 ]; then
    echo "Installing Homebrew"
    echo

    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    echo "Installing yaml"
    echo

    brew install libyaml
fi

# install ruby

COUNT=`brew list | grep ruby | wc -l`
if [ "${COUNT}" == 0 ]; then
    echo "Installing ruby"
    echo

    brew install ruby
fi

# install chromedriver

if [ ! -f "/usr/local/bin/chromedriver" ]; then
    echo "Installing chromedriver"
    echo

    DEST=chromedriver_mac64.zip
    curl https://chromedriver.storage.googleapis.com/2.37/chromedriver_mac64.zip -o $DEST
    unzip $DEST -d /usr/local/bin
fi

# install selenium
echo "Installing selenium webdriver gem"
echo
    sudo gem install selenium-webdriver -v 2.53.4

# install Codacy Coverage and allow locally executed framework tests to be recorded in Codacy
echo "Installing selenium webdriver gem"
echo
    sudo gem install codacy-coverage
    export CODACY_PROJECT_TOKEN=7e4dfd7f11e5449096984c9ea67fe5dc
    export CODACY_RUN_LOCAL=true

echo "######################################################################"
echo "Installation completed"
echo "######################################################################"

