#!/bin/bash
######################################################################
# Avenir Technology GUI testing
######################################################################
SCRIPT=${@: -1}
BROWSER=''
DIRECTORY=''
STATS_DIR=''
while getopts "b:s:d:g:p" opt; do
  case $opt in
    b)
      BROWSER="$OPTARG"
      # echo "-b $BROWSER was triggered!" >&2
      ;;
    s)
      SCRIPT="$OPTARG"
      # echo "-s $SCRIPT was triggered!" >&2
      ;;
    d)
      DIRECTORY="$OPTARG"
      # echo "-d $DIRECTORY was triggered!" >&2
      ;;
    g)
      STATS_DIR="$OPTARG"
      # echo "-g $DIRECTORY was triggered!" >&2
      ;;
    p)
      DIRECTORY="/Users/siennahendrikx/Dropbox\ \(Personal\)/test\ results/"
      # echo "-p $DIRECTORY was triggered!" >&2
      ;;
    \?)
      echo "Invalid flag. Examples of valid flag calls:" >&2
      echo "-d path/to/results/directory"
      echo "-b chrome"
      echo "-s scripts/test.txt"
      echo "-g path/to/results/directory   or -g current <-- (current/results/directory)"
      echo "-p <-- (sets directory to Dropbox)"
      exit 1;
      ;;
  esac
done
if [ -z "$BROWSER" ]; then
    BROWSER="chrome"
fi

if [ -z "$DIRECTORY" ]; then
    DIRECTORY="results/"
fi

if [ -z "$STATS_DIR" ]; then
    STATS_DIR="no_stats"
fi

ruby main.rb $BROWSER $SCRIPT $DIRECTORY $STATS_DIR
